### ISSUE TITLE
Failure to run on ARM/M2

### ISSUE THREAD

**Issue by iloveitaly** [gliderlabs/herokuish#1018]
The macOS binary (albeit compiled for x86) failed to run:

```
dyld[39000]: Library not loaded: /usr/local/opt/gettext/lib/libintl.8.dylib
  Referenced from: <560CCD2E-10B3-3F09-AC49-AB40D4C49112> /Users/mike/.basher/bash
  Reason: tried: '/usr/local/opt/gettext/lib/libintl.8.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/opt/gettext/lib/libintl.8.dylib' (no such file), '/usr/local/opt/gettext/lib/libintl.8.dylib' (no such file), '/usr/local/lib/libintl.8.dylib' (no such file), '/usr/lib/libintl.8.dylib' (no such file, not in dyld cache)
2023/08/23 07:54:44 signal: abort trap
```

I tried building the application locally, and it failed, I think [because of the `cd /` lines](https://github.com/gliderlabs/herokuish/blob/77da1de18694eec3f366e7ccb14dcfdd28f11c26/Makefile#L131).

Here's a snippet of the failure:

```
mkdir -p $WORK/b001/exe/
cd .
/opt/homebrew/Cellar/go/1.19.4/libexec/pkg/tool/darwin_arm64/link -o $WORK/b001/exe/a.out -importcfg $WORK/b001/importcfg.link -buildmode=exe -buildid=4gMU95uRQO7Ou_CNylYe/pbGUFIjrUCCTdUFDFL9B/mN64kN_8bPaL_xR1oNRT/4gMU95uRQO7Ou_CNylYe -extld=clang $WORK/b001/_pkg_.a
/opt/homebrew/Cellar/go/1.19.4/libexec/pkg/tool/darwin_arm64/buildid -w $WORK/b001/exe/a.out # internal
mkdir -p /Users/mike/go/bin/
mv $WORK/b001/exe/a.out /Users/mike/go/bin/go-bindata
rm -r $WORK/b001/
go-bindata include
make: go-bindata: No such file or directory
make: *** [bindata.go] Error 1
```

I'm not familiar with go, so I wasn't sure where to go (ha!) from here.

**Comment by josegonzalez** [comment]
This is unfortunately not really meant to be run on macOS - not sure why we compile for that platform tbh - but on Linux (preferably in a container)

What exactly are you trying to do?

**Comment by iloveitaly** [comment]
@josegonzalez ah, got it! Wasn't super clear from the docs/releases that you _couldn't_ run this on macOS and it should really be run within an intel-architecture docker container. I'll submit a PR to make that a bit more clear in the docs.

Question on debugging a build: is there a way to jump into the builder container and run/tinker with a build pack that is failing? Outside of `-e TRACE=true` what other ways can I disable a build pack?

**Comment by josegonzalez** [comment]
I normally fork the buildpack and add set -x calls as appropriate.

Here is a blog post that describes running herokuish locally for testing, outside of dokku: https://dokku.com/blog/2020/comparing-buildpack-v3-to-herokuish/
