### ISSUE TITLE
Permission denied on /tmp directory

### ISSUE THREAD

**Issue by ignlg** [gliderlabs/herokuish#105]
Since I updated the herokuish image, I cannot compile nginx as a build step due to:

```
...
mkdir: cannot create directory '/tmp/cg2779-8969': Permission denied
mkdir: cannot create directory '/tmp/cg-2779': Permission denied
...
```

I've mounted a container to check it and these are the `/tmp` permissions:
```
# stat -c '%a %n' /tmp
1755 /tmp
```

Changing permissions to standard
```
# chmod 1777 /tmp
```
fixes the compilation issue, as expected.

Shouldn't it be world-writable as in any standard *nix setup?

**Comment by ignlg** [comment]
Pulling latest image fixed the issue. Something weird happening on Dokku setup.

**Comment by josegonzalez** [comment]
> Since I updated the herokuish image

and

> Pulling latest image fixed the issue

Sounds like maybe you didn't pull the latest version? :)

**Comment by ignlg** [comment]
@josegonzalez  It happened using the herokuish installed via apt (with an `apt-get update`). I fixed it with a manual `docker pull gliderlabs/herokuish` but the issue is still there, somewhere in the setup process via apt.
