### ISSUE TITLE
how to deploy app

### ISSUE THREAD

**Issue by SolarisYan** [gliderlabs/herokuish#113]
can i use herokuish to deploy my app? i can use 
docker run --rm -v /abs/app/path:/tmp/app gliderlabs/herokuish /bin/herokuish test
to test my app,but how to deploy it?
anyone can help me?

**Comment by josegonzalez** [comment]
Herokuish doesn't "deploy" applications. You can use it to create docker images, and then use some other tool to start those containers elsehwere.

You should read the documentation on [docker images](https://docs.docker.com/engine/userguide/containers/dockerimages/#creating-our-own-images) for more details.

**Comment by SolarisYan** [comment]
@josegonzalez got it,thx
