### ISSUE TITLE
Slowness on App start

### ISSUE THREAD

**Issue by singlow** [gliderlabs/herokuish#114]
I am using herokuish in dokku and there is a long delay before app starts. I have narrowed it down to this line:
 
https://github.com/gliderlabs/herokuish/blob/master/include/procfile.bash#L91

Since the container image is AUFS, the chown is causing every single file in /app to be modified, which means copying every file. Chown may be the most efficient under normal circumstances, but when it is causing the file to be copied due to a copy-on-write filesystem, it often takes 5-10 minutes. This even though there are only a few files that aren't already owned by the unprivileged user. Maybe overlay-fs would not have this issue - I don't have it set up anywhere to test.

I am testing a patch to do
```
find /app \! -user $unprivileged_user | xargs -0 -r chown $unprivileged_user:$unprivileged_group
```
Which at least prevents writing every file and in my case runs in a few seconds compared to 3-10 min.

Is this affecting others, or is there something I can do differently to avoid this?

**Comment by josegonzalez** [comment]
@singlow your patch should also check for the unprivileged group (maybe a separate `find|xargs` call). I'd be happy to merge that :)
