### ISSUE TITLE
config_vars section from .release ignored

### ISSUE THREAD

**Issue by sergium** [gliderlabs/herokuish#115]
Problem:
  - Heroku's build-packs not compatible with dokku after the dokku's migration from the buildsteps to herokuish

Example:
  - https://github.com/heroku/heroku-buildpack-erlang
  - config_vars section from the bin/release ignored
```
   config_vars:
     PATH: /app/otp/bin:bin:/usr/bin:/bin
```
  - as result container that is startable on Heroku now not startable on the dokku  
 

More details (reported as dokku-issue) here: https://github.com/dokku/dokku/issues/1972

**Comment by michaelshobbs** [comment]
Root cause can be found here: https://github.com/dokku/dokku/issues/1972#issuecomment-193004819
