### ISSUE TITLE
how to start the app

### ISSUE THREAD

**Issue by SolarisYan** [gliderlabs/herokuish#131]
after i build the app with docker,and i commit it to a image,but how to start the app? use /start ? 
in addition,after i build the app,how can i export the /app,when i use "herokuish slug generate",but only include the src app?

**Comment by michaelshobbs** [comment]
Did you get the answer you needed from #111?

**Comment by SolarisYan** [comment]
@michaelshobbs yes,now i get the whole flow,thx
