### ISSUE TITLE
can i build herokuish  on other os

### ISSUE THREAD

**Issue by SolarisYan** [gliderlabs/herokuish#132]
i think the size of image gliderlabs/herokuish  is a bit big,it have  1.307 GB .so i want to build the herokuish with other os from the src code? can i ? if yes ,and how?

**Comment by michaelshobbs** [comment]
herokuish is based on the Heroku cedar14 image. That's where all of the bulk is coming from. The buildpacks need a bunch of supporting packages in order to do their thing. 

The commands to build herokuish are all in the Makefile for reference

**Comment by SolarisYan** [comment]
@michaelshobbs got it,thank you
