### ISSUE TITLE
Detect appropriate buildpack like Heroku

### ISSUE THREAD

**Issue by michaelshobbs** [gliderlabs/herokuish#133]
- We'd like to detect the appropriate buildpack in the same order as Heroku
  - https://devcenter.heroku.com/articles/buildpacks
- Additionally, we'd like to show **all** valid buildpacks for an app
<img width="936" alt="image 2016-03-29 at 6 05 39 pm" src="https://cloud.githubusercontent.com/assets/4491438/14125414/e8fbc07c-f5bf-11e5-9478-b926545c8c6c.png">

**Comment by josegonzalez** [comment]
The screenshot comes from [this page](http://foundation.zurb.com/forum/posts/23119-deploy-foundation-for-apps-on-heroku).

**Comment by michaelshobbs** [comment]
Issue in the wild dokku/dokku#2151
