### ISSUE TITLE
where are the executable now? 

### ISSUE THREAD

**Issue by MatthewMueller** [gliderlabs/herokuish#16]
When running a compiled node image, it works if I run `/start web`, but doesn't work if I just call `npm` or `node`.

Higher-level, it doesn't seem possible to execute files with these binaries in Dokku plugins, so for example in a node script:

```js
#!/usr/bin/env node

console.log('hi');
```

Will not be able to find the `node` executable, if I just try to run them on the container via:

```
COMMAND=$(cat <<EOF
cd "/app" &&
make build
EOF
)

id=$(docker run -d $IMAGE /bin/bash -c "$COMMAND")
docker attach $id
test $(docker wait $id) -eq 0
docker commit $id $IMAGE > /dev/null
```

Is there something I need to update in the plugins for herokuish?

**Comment by MatthewMueller** [comment]
Ahh cool, looks like I can just run `/exec make build` now. 

Looks like some folks are going to need to update their plugins though, haha.

**Comment by progrium** [comment]
Can you tell me exactly what was being run before and *how*?

On Sun, Mar 29, 2015 at 9:34 PM, Matthew Mueller <notifications@github.com>
wrote:

> Closed #16 <https://github.com/gliderlabs/herokuish/issues/16>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gliderlabs/herokuish/issues/16#event-268101525>.
>



-- 
Jeff Lindsay
http://progrium.com

**Comment by MatthewMueller** [comment]
**before**

You could just do something like..

```bash
$ local        > ssh dokku@dokku.me run $APP /bin/bash
$ container    > node
$ node REPL    > console.log('hi');
hi 
```

Now:

```bash
$ local        > ssh dokku@dokku.me run $APP /bin/bash
$ container    > node
Error node not found
```

But this works:

```bash
$ local         > ssh dokku@dokku.me run $APP /bin/bash
$ container     > /exec node
$ node REPL     > console.log('hi');
hi 
```

**Comment by progrium** [comment]
Interesting. Dokku might need to update `run` to pass through `/exec` and then using `/exec` won't be necessary. cc @josegonzalez

**Comment by josegonzalez** [comment]
What does /exec do in this context?

**Comment by progrium** [comment]
https://github.com/gliderlabs/herokuish/blob/master/include/procfile.bash#L14-L22

Among other things, it sets up the correct PATH.

**Comment by MatthewMueller** [comment]
Ohhhh +1

**Comment by josegonzalez** [comment]
I think we already pass the commands via `/exec` [here](https://github.com/progrium/dokku/blob/master/plugins/00_dokku-standard/commands#L141-L154)?

**Comment by MatthewMueller** [comment]
Yikes, false alarm guys. It's working in the latest release `0.3.16`. Thanks for the support!

**Comment by MatthewMueller** [comment]
Thinking about it a bit more, this is definitely a breaking change for a lot of plugins I've seen, for example: https://github.com/MatthewMueller/dokku-make-build-plugin/blob/master/post-release#L12-L16

**Comment by progrium** [comment]
It sure is! Good thing Dokku is pre-1.0 and there was a warning to plugin
authors... :P

On Mon, Mar 30, 2015 at 10:09 PM, Matthew Mueller <notifications@github.com>
wrote:

> Thinking about it a bit more, this is definitely a breaking change for a
> lot of plugins I've seen, for example:
> https://github.com/MatthewMueller/dokku-make-build-plugin/blob/master/post-release#L12-L16
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gliderlabs/herokuish/issues/16#issuecomment-87917917>.
>



-- 
Jeff Lindsay
http://progrium.com
