### ISSUE TITLE
Confused about exec vs. start & creating a runnable image

### ISSUE THREAD

**Issue by pvencill** [gliderlabs/herokuish#179]
I was following the example given in #62 to create a runnable image.  When I used their sample dockerfile to do so, I made one modification to the code to have it call `npm start` rather than the specific file stuff, since I always run my node apps that way.  The result was as follows:

`FROM gliderlabs/herokuish

RUN mkdir -p /app
COPY . /app
RUN /build

ENTRYPOINT ["/exec", "npm", "start]`

This builds fine, but running it results in the error: `setuidgid: usage: setuidgid account child`

Conversely, if I change it to rely on a Procfile and simply change the last line to 

`ENTRYPOINT ["/start", "web"]`

It works as expected, and I can navigate to my app through the exposed port. 

Given that the Procfile defines `web: npm start`, I'm confused as to why I get the error on exec but not on start.  Any suggestions as to why this might be the case?  The docs say 

> start                    Run process type command from Procfile through exec

Which seems to indicate that exec is still being run under the hood.

**Comment by michaelshobbs** [comment]
Bare with me while I walk us (mostly me) through the execution path.

So, looking at the code, we map `/start` and `/exec` [thusly](https://github.com/gliderlabs/herokuish/blob/v0.3.18/include/herokuish.bash#L150-L151).

Indeed `procfile-start` calls `procfile-exec` [here](https://github.com/gliderlabs/herokuish/blob/v0.3.18/include/procfile.bash#L30-L44).

I know that flow works as we use it in dokku for all of our tests and out in the wild. 

Looking at what you originally reported, it seems there is a missing double quotation mark in your `ENTRYPOINT` directive around `start`.

> ENTRYPOINT ["/exec", "npm", "start]`

Not sure if that was missed in translation when you opened the issue or it was actually a copy/paste and thus broken in your `Dockerfile`.

Let us know if that's the case and whether remedying that resolves your issue or not.

**Comment by pvencill** [comment]
Thanks for the explanation.  So the entrypoint I posted above was not a copy/paste from the Dockerfile, I just typed it here (missing the closing quote).  

I tried rebuilding and re-running the exec version (no changes to the Dockerfile) and it works fine now, I'm at a loss as to why but since I can't repeat it at this point I'll close the issue.

**Comment by michaelshobbs** [comment]
Hrm. Very odd indeed. Let us know if it pops back up.
