### ISSUE TITLE
Multiline execs

### ISSUE THREAD

**Issue by MatthewMueller** [gliderlabs/herokuish#18]
This is *probably* a bash issue, but I could use some guidance and some other people could use this as a reference.

I'm really struggling to execute a multi-line command within a container:

```bash
makehook() {
  IMAGE=$1
  HOOK=$2

  COMMAND=$(cat <<EOF
[[ -f "Makefile" ]]
&& grep -q "^$HOOK:" Makefile
&& echo "------> Triggering: make $HOOK"
&& make $HOOK
&& echo "------> Triggered: make $HOOK"
EOF
)

  id=$(docker run -d $IMAGE /exec "$COMMAND")
  docker attach $id
  test "$(docker wait $id)" -eq 0
  docker commit $id $IMAGE > /dev/null
}
```

Yields the following:

```
remote: /bin/bash: line 1: ------: command not found
remote: /bin/bash: line 2: dokku.post-build-buildstep: command not found
remote: /bin/bash: line 3: ------: command not found
```

Basically, I think it's the arrows. It'd be nice to have them outside the container, but I only want output if the file exists.

/cc @michaelshobbs @josegonzalez (if you can take a look too, I've spent hours on this issue :-X)

**Comment by MatthewMueller** [comment]
If I run it inside the container, no problems:

```
![image](https://cldup.com/dSZBHEGzg6.png)
```

**Comment by progrium** [comment]
Bash lexical evaluation is basically impossible to reason about beyond one layer of indirection because of quoting and potential mistakes. I would just avoid it because once you figure it out it will not be maintainable. Solve by redesign. Can you make this exist as a parameterized script inside the image?

**Comment by MatthewMueller** [comment]
Yah... haha. I ended up breaking it apart, which makes much more sense:

https://github.com/MatthewMueller/dokku-make-hook/blob/master/make-hook#L8-L16

Thanks for your response!
