### ISSUE TITLE
Unable to use custom buildpack

### ISSUE THREAD

**Issue by sosedoff** [gliderlabs/herokuish#186]
Im not sure if im doing something wrong or its a legit issue. Tried testing the application (both on OSX and Linux) with a custom static buildpack. Build command always exited with non-zero status.
I dont thinks is an issue with **that** particular buildpack, using any third-party one resulted in the same problem.

In the test application i created file `.buildpacks` with the following content:

```
https://github.com/abhishekmunie/heroku-buildpack-static.git
```

Then ran test command:

```
 docker run --rm -e TRACE=1 -v $(pwd):/tmp/app gliderlabs/herokuish /bin/herokuish test
```

Here's the tail of the log:

```
+ selected_path=/tmp/buildpacks/00_buildpack-multi
++ unprivileged /tmp/buildpacks/00_buildpack-multi/bin/detect /tmp/build
++ setuidgid u2143 /tmp/buildpacks/00_buildpack-multi/bin/detect /tmp/build
+ selected_name=Multipack
+ [[ -n /tmp/buildpacks/00_buildpack-multi ]]
+ [[ -n Multipack ]]
+ title 'Multipack app detected'
----->' Multipack app detected
-----> Multipack app detected == --* ]]
-----> Multipack app detected == ==* ]]
-----> Multipack app detected'
-----> Multipack app detected
+ read line
+ cd /tmp/build
+ unprivileged /tmp/buildpacks/00_buildpack-multi/bin/compile /tmp/build /tmp/cache /tmp/env
+ setuidgid u2143 /tmp/buildpacks/00_buildpack-multi/bin/compile /tmp/build /tmp/cache /tmp/env
+ [[ =====> Downloading Buildpack: https://github.com/abhishekmunie/heroku-buildpack-static.git == --* ]]
+ [[ =====> Downloading Buildpack: https://github.com/abhishekmunie/heroku-buildpack-static.git == ==* ]]
=====>' Downloading Buildpack: https://github.com/abhishekmunie/heroku-buildpack-static.git
=====> Downloading Buildpack: https://github.com/abhishekmunie/heroku-buildpack-static.git
+ read line
```

Test command just exists and there's no error or anything useful in the log.
Using latest `gliderlabs/herokuish` docker image. Versions:

```
herokuish: 0.3.19
buildpacks:
  heroku-buildpack-multi     v1.0.0
  heroku-buildpack-ruby      v146
  heroku-buildpack-nodejs    v91
  heroku-buildpack-clojure   v75
  heroku-buildpack-python    v82
  heroku-buildpack-java      v46
  heroku-buildpack-gradle    v18
  heroku-buildpack-grails    v21
  heroku-buildpack-scala     v72
  heroku-buildpack-play      v26
  heroku-buildpack-php       v110
  heroku-buildpack-go        v44
  heroku-buildpack-erlang    fa17af9
  buildpack-nginx            v6
  emberjs.tgz                latest
```

**Comment by michaelshobbs** [comment]
It looks like this particular invocation is getting stuck on the multi buildpack. If you only need to specify a single buildpack, it would probably be best to simplify this by removing `.buildpacks` and adding a `.env` file to the root of your repo with the following contents:

```
export BUILDPACK_URL=https://github.com/abhishekmunie/heroku-buildpack-static.git
```

Give that a shot with `TRACE=1` and let us know what you see.

**Comment by sosedoff** [comment]
Ok, i'll give it a try, however, i suspect there's something going on with heroku's multipack buildpack itself. I've tested a few different scenarios but haven't figured out the root cause yet. Again, using the same buildpack on heroku works, so it might as well be my local issue.

**Comment by michaelshobbs** [comment]
Yeah it's almost certainly a local issue. I assumed you were wanting to troubleshoot deploying your app with the static buildpack and not the multi buildpack. Was trying to simplify the troubleshoot no process. 

In order to do the latter you'll want to start a herokuish container with the same mounts and env but instead of running the `herokuish` binary, execute `bash`. From there you can edit the local buildpack files in `/tmp/buildpacks` to spit out more debugging detail.

**Comment by michaelshobbs** [comment]
It should be noted (for those that might find themselves here from Google searches) that the preferred method of specifying a custom buildpack is to either pass `-e BUILDPACK_URL=...` or include a `.env` file in the root of your repo exporting that same environment variable.

**Comment by sosedoff** [comment]
Btw, could you reproduce the issue? Here's what i did:

1. Created a new dir with only file `.buildpacks`
2. Added the following buildpacks:

```
https://github.com/heroku/heroku-buildpack-ruby.git
https://github.com/heroku/heroku-buildpack-php.git
```
3. Ran `docker run --rm -e TRACE=1 -v $(pwd):/tmp/app gliderlabs/herokuish /bin/herokuish test`.

So if you have valid ruby app (Gemfile present) then everything works, but if there's no ruby stuff in the dir test command fails with no error output. Exit code is set to 1.

**Comment by michaelshobbs** [comment]
Oh that's different than the original issue. (You had said you were using the static bp.) I'm happy to attempt to reproduce the problem. Do you have a sample app repo I can test with?

**Comment by sosedoff** [comment]
Yeah, the issue seems to be slightly different. Here's the test repo: https://github.com/sosedoff/herokuish-issue-186
Clone and run: `./test.sh`

**Comment by sosedoff** [comment]
Whats more interesting, i forked heroku's multipack builpack repo and added some instrumentations. Here's the line that triggers the exit:

https://github.com/heroku/heroku-buildpack-multi/blob/master/bin/compile#L44

**Comment by michaelshobbs** [comment]
Yeah that happens because the ruby buildpack doesn't detect your app as compatible.

See here:
https://github.com/heroku/heroku-buildpack-ruby/blob/master/bin/detect#L7

**Comment by sosedoff** [comment]
Closing this for now since the issue is not related to herokuish.
