### ISSUE TITLE
latest nodejs buildpack fails with permission denied

### ISSUE THREAD

**Issue by michaelshobbs** [gliderlabs/herokuish#19]
Using this sample repo fork (https://github.com/michaelshobbs/node-js-sample) I get the following permission denied error when deploying with dokku.

```
-----> Checking startup method
       Found Procfile

-----> Finalizing build
       Creating runtime environment
remote: /tmp/buildpacks/custom/lib/build.sh: line 212: /tmp/buildpacks/custom/export: Permission denied
       Exporting binary paths

-----> Build failed

       We're sorry this build is failing! If you can't find the issue in application code,
       please submit a ticket so we can help: https://help.heroku.com/
       You can also try reverting to our legacy Node.js buildpack:
       heroku config:set BUILDPACK_URL=https://github.com/heroku/heroku-buildpack-nodejs#v63

       Love,
       Heroku
```

```
root@c14760c734ec:/# ls -la /tmp/buildpacks/
total 60
drwxr-xr-x 27 u29276 u29276 4096 Mar 30 23:18 .
drwxrwxrwt 13 root   root   4096 Mar 30 23:18 ..
drwxr-xr-x  6 root   root   4096 Mar 30 23:18 custom
drwxr-xr-x 10 u29276 u29276 4096 Mar 30 23:18 heroku-buildpack-clojure
drwxr-xr-x 12 u29276 u29276 4096 Mar 30 23:18 heroku-buildpack-go
drwxr-xr-x 12 u29276 u29276 4096 Mar 30 23:18 heroku-buildpack-gradle
drwxr-xr-x  6 u29276 u29276 4096 Mar 30 23:18 heroku-buildpack-grails
drwxr-xr-x 12 u29276 u29276 4096 Mar 30 23:18 heroku-buildpack-java
drwxr-xr-x  4 u29276 u29276 4096 Mar 30 23:18 heroku-buildpack-multi
drwxr-xr-x  8 u29276 u29276 4096 Mar 30 23:18 heroku-buildpack-nodejs
drwxr-xr-x  8 u29276 u29276 4096 Mar 30 23:18 heroku-buildpack-php
drwxr-xr-x 10 u29276 u29276 4096 Mar 30 23:18 heroku-buildpack-play
drwxr-xr-x  8 u29276 u29276 4096 Mar 30 23:18 heroku-buildpack-python
drwxr-xr-x 14 u29276 u29276 4096 Mar 30 23:18 heroku-buildpack-ruby
drwxr-xr-x 14 u29276 u29276 4096 Mar 30 23:18 heroku-buildpack-scala
root@c14760c734ec:/# ls -la /tmp/buildpacks/custom/
total 44
drwxr-xr-x  6 root   root   4096 Mar 30 23:18 .
drwxr-xr-x 27 u29276 u29276 4096 Mar 30 23:18 ..
-rw-r--r--  1 root   root     17 Mar 30 23:18 .gitignore
-rw-r--r--  1 root   root   1075 Mar 30 23:18 LICENSE
-rw-r--r--  1 root   root   7008 Mar 30 23:18 README.md
drwxr-xr-x  2 root   root   4096 Mar 30 23:18 bin
-rw-r--r--  1 root   root   1391 Mar 30 23:18 concurrency
drwxr-xr-x  2 root   root   4096 Mar 30 23:18 lib
drwxr-xr-x  3 root   root   4096 Mar 30 23:18 test
drwxr-xr-x  2 root   root   4096 Mar 30 23:18 vendor
```
EDIT: I believe this to be the offending code. However, this is fairly irrelevant since `/tmp/buildpacks/custom` should probably be owned by the anonymous user? 

https://github.com/heroku/heroku-buildpack-nodejs/blob/40214da800dadf60b9a746514ea55140f5863380/lib/build.sh#L210-L214

ref: https://github.com/progrium/buildstep/issues/145

**Comment by progrium** [comment]
Yeah I'm not exactly sure why `/tmp/buildpacks/custom` is not properly set up. It *should* be an easy fix, but I haven't looked yet.

**Comment by alex88** [comment]
Same error here with the ruby buildpack after and including version 130

**Comment by silverwind** [comment]
Just hit the same issue.

**Comment by patrickjahns** [comment]
This issue only seem to occure when using the v71 buildpack as a custom buildpack vs preinstalling it.

It seems that the permissions are not properly set for /tmp/buildpacks/custom or the other way around, the (unprivileged?) user has not enough rights to write there? 

It doesn`t seem obvious to me, but when the download of a custom buildpack is done, is it executed as root or already as unprivileged user?

**Comment by alex88** [comment]
Can we have a new version to be used with buildstep?

**Comment by patrickjahns** [comment]
If you need it urgently, just build it yourself and rebuild the buildstep container on the machine where you use it

If you don`t want to install go, then just use the google/golang Dockerfile for it.
For reference see my 32bit repository [make.sh](https://github.com/dokku32bit/herokuish_32bit/blob/master/make.sh) and [build.sh](https://github.com/dokku32bit/herokuish_32bit/blob/master/build.sh) - just replace the docker continer in make.sh with google/golang and you shall be fine.

For creating the buildstep image, instead of downloading, just copy the file in the respective directory inside the Docker container and execute the scripts

**Comment by alex88** [comment]
Thanks for the info @patrickjahns. It's not that urgent to do that, I'll wait :wink:

**Comment by progrium** [comment]
Really you should just use Herokuish instead of Buildstep. Dokku should be
doing this soon. Somebody should submit a PR so it can happen sooner than
when I get around to it.

On Mon, Apr 20, 2015 at 7:45 AM, Alessandro Tagliapietra <
notifications@github.com> wrote:

> Thanks for the info @patrickjahns <https://github.com/patrickjahns>. It's
> not that urgent to do that, I'll wait [image: :wink:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gliderlabs/herokuish/issues/19#issuecomment-94442760>.
>



-- 
Jeff Lindsay
http://progrium.com

**Comment by michaelshobbs** [comment]
@progrium can you be more specific? what exactly needs to be done? is it just pulling a particular image from docker hub instead of downloading the buildstep release? in any case, drop the info here and I can PR it up.

**Comment by progrium** [comment]
Yeah that's basically it. Right now Buildstep is pulled from a tgz on S3 in
the Makefile. Instead it should just pull gliderlabs/herokuish from Docker
Hub. Any reference to buildstep then just needs to change to herokuish.

People wanted to be able to use their own base image in Dokku, but you can
still achieve this by loading it however and tagging it as
gliderlabs/herokuish.

Thanks!

On Mon, Apr 20, 2015 at 1:28 PM, Michael Hobbs <notifications@github.com>
wrote:

> @progrium <https://github.com/progrium> can you be more specific? what
> exactly needs to be done? is it just pulling a particular image from docker
> hub instead of downloading the buildstep release? in any case, drop the
> info here and I can PR it up.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gliderlabs/herokuish/issues/19#issuecomment-94531129>.
>



-- 
Jeff Lindsay
http://progrium.com

**Comment by patrickjahns** [comment]
@michaelshobbs 

I will gladly help with the PR 

Let`s move this to https://github.com/progrium/dokku/issues/1091

**Comment by michaelshobbs** [comment]
:+1:
