### ISSUE TITLE
Silent failure if daemontools isn't installed

### ISSUE THREAD

**Issue by durkode** [gliderlabs/herokuish#205]
I ran herokuish against my django app, using the default python:3.5 docker image. When running 'herokuish test', it complained that it was 'Unable to select a buildpack'. The buildpack detect function worked fine when run as root, and it was only after some digging that I realised my docker image didn't have the 'setuidgid' function, and such was failing silently. Installing daemontools in the container fixed the problem.

It would be good if there was a warning / check for this without failing silently.

**Comment by michaelshobbs** [comment]
Thanks for the report. We'd definitely welcome a PR for that.

**Comment by durkode** [comment]
Sure thing, will submit one soon

**Comment by lxfontes** [comment]
and for those on runit:
`sudo ln -s /usr/bin/chpst /usr/bin/setuidgid`

**Comment by shuhaowu** [comment]
Maybe this could be added into the readme?

**Comment by josegonzalez** [comment]
Pull requests welcome.

**Comment by josegonzalez** [comment]
Note: `daemontools` is now installed by default, so this isn't necessary anymore.
