### ISSUE TITLE
start exited with no output

### ISSUE THREAD

**Issue by FLYBYME** [gliderlabs/herokuish#216]
Im having a hard time figuring out why when I run `herokuish procfile start web` it does not start the application and just exits.

```
# ls -a /app/
.  ..  .heroku  .profile.d  .project  .release  Dockerfile  
Procfile  a  node_modules  package.json  server.j


# ls -a /tmp/app
.  ..  .heroku  .profile.d  .project  .release  Dockerfile  
Procfile  a  node_modules  package.json  server.js

# cat /app/Procfile 
web: node server.js

# ls /app/.profile.d/
nodejs.sh


# cat /app/.profile.d/nodejs.sh 
calculate_concurrency() {
  MEMORY_AVAILABLE=${MEMORY_AVAILABLE-$(detect_memory 512)}
  WEB_MEMORY=${WEB_MEMORY-512}
  WEB_CONCURRENCY=${WEB_CONCURRENCY-$((MEMORY_AVAILABLE/WEB_MEMORY))}
  if (( WEB_CONCURRENCY < 1 )); then
    WEB_CONCURRENCY=1
  fi
  WEB_CONCURRENCY=$WEB_CONCURRENCY
}

log_concurrency() {
  echo "Detected $MEMORY_AVAILABLE MB available memory, $WEB_MEMORY MB limit per process (WEB_MEMORY)"
  echo "Recommending WEB_CONCURRENCY=$WEB_CONCURRENCY"
}

detect_memory() {
  local default=$1
  local limit=$(ulimit -u)

  case $limit in
    256) echo "512";;      # Standard-1X
    512) echo "1024";;     # Standard-2X
    16384) echo "2560";;   # Performance-M
    32768) echo "14336";;  # Performance-L
    *) echo "$default";;
  esac
}

export PATH="$HOME/.heroku/node/bin:$HOME/.heroku/yarn/bin:$PATH:$HOME/bin:$HOME/node_modules/.bin"
export NODE_HOME="$HOME/.heroku/node"
export NODE_ENV=${NODE_ENV:-production}

calculate_concurrency

export MEMORY_AVAILABLE=$MEMORY_AVAILABLE
export WEB_MEMORY=$WEB_MEMORY
export WEB_CONCURRENCY=$WEB_CONCURRENCY

if [ "$LOG_CONCURRENCY" = "true" ]; then
  log_concurrency
fi
```

This is the trace output.ls /ap
https://gist.github.com/FLYBYME/a6e9cf6d5efaacc1342e0c212b27d828

**Comment by FLYBYME** [comment]
These are the scripts im running to create and then run the application.

build.sh

```sh
#!/bin/bash


echo "-----> Pulling application"
wget $APP_URL -O /tmp/app.tar 2> /dev/null
if [ $? -eq 0 ];then
	echo "       Extracting application"
else
	echo "       Application download fail"
	exit 1
fi


tar -xf /tmp/app.tar -C /app 2> /dev/null
if [ $? -eq 0 ];then
	echo "       Extraction complete"
else
	echo "       Application extraction fail"
	exit 1
fi



echo "-----> Pulling cache"
if wget $CACHE_URL -O /tmp/cache.tar 2> /dev/null ; then
	echo "       Extracting cache"
	tar -xzf /tmp/cache.tar -C /tmp 2> /dev/null
	if [ $? -eq 0 ];then
		echo "       Extraction complete"
	else
		echo "       Cache extraction fail"
	fi
	mv /tmp/tmp/cache /tmp 2> /dev/null
else
	echo "       No cache found"
fi

if [ "$BUILDPACK" != "" ]; then
	echo "-----> Downloading buildback"
	echo "       Buildback url: $BUILDPACK"
	/bin/herokuish buildpack install $BUILDPACK 2> /dev/null
	if [ $? -eq 0 ];then
		echo "       Download complete"
	else
		echo "       Buildback download fail"
		exit 1
	fi
fi

/bin/herokuish buildpack build
if [ $? -eq 0 ];then
	echo "-----> Build complete"
else
	echo "-----> Build fail"
	exit 1
fi

echo "-----> Packing build"
echo "       Compressing build"
tar -czf /tmp/build.tar /app 2> /dev/null
if [ $? -eq 0 ];then
	echo "       Compression complete"
else
	echo "       Compression fail"
	exit 1
fi

echo "       Pushing build"
mc cp --quiet /tmp/build.tar s3/$APP_UPLOAD_PATH > /dev/null
if [ $? -eq 0 ];then
	echo "       Push complete"
else
	echo "       Push fail cannot run without the build"
	exit 1
fi


echo "-----> Packing cache"
echo "       Compressing cache"
tar -czf /tmp/cache.tar /tmp/cache 2> /dev/null
if [ $? -eq 0 ];then
	echo "       Compression complete"
else
	echo "       Compression fail will skip cache next time"
fi

echo "       Pushing cache"
mc cp --quiet /tmp/cache.tar s3/$CACHE_UPLOAD_PATH > /dev/null
if [ $? -eq 0 ];then
	echo "       Push complete"
else
	echo "       Push fail will skip cache next time"
fi

exit 0
```

and this is the runner
run.sh
```sh
#!/bin/bash
set -m

PROC_TYPE=$1
BUILD_URL=$2
echo $PROC_TYPE
echo $BUILD_URL


wget $BUILD_URL -O /tmp/app.tar 
mkdir /app
tar -xf /tmp/app.tar -C / 

run_cmd="/bin/herokuish"

run_cmd="$run_cmd procfile start $PROC_TYPE"
TRACE=true
$run_cmd &


fg
```

**Comment by michaelshobbs** [comment]
Can you provide the entire `docker run` cmd your are attempting to execute?

**Comment by FLYBYME** [comment]
I dont know how else to show the work flow so I just used a public s3 host.

This is the work flow you can see https://github.com/MangoRaft/cedar

All Im doing is building the app in one container and the uploading the tar file to s3. Then I am downloading the uploaded tar file to a second container and trying to run it.

Im trying to save myself from creating a docker image for every build of an application.

**Comment by michaelshobbs** [comment]
Apologies but I'm not following. How are you executing the second container?

**Comment by FLYBYME** [comment]
Yes I'm building the application in one container and running it in another. That is without creating a docker image.

**Comment by michaelshobbs** [comment]
Can you provide the `docker` command you are using for both containers please?

**Comment by FLYBYME** [comment]
They are in the readme in the repo that I linked.

**Comment by michaelshobbs** [comment]
Those commands don't reference `herokuish` at all.

**Comment by FLYBYME** [comment]
https://github.com/MangoRaft/cedar/tree/master/runner is almost a copy of https://github.com/tt/stack-images.

herokuish runs on the image.

**Comment by michaelshobbs** [comment]
Ah ok! That makes more sense. 

So `herokuish` will attempt to run your app as an unprivileged user. The default user (`herokuishuser`) is included in the image for your use. If you don't pass in the `USER` env var `herokuish` will attempt to detect the user by running `stat -c %U /app` [here](https://github.com/gliderlabs/herokuish/blob/8ca51f4f408c8239ab1bf0f342e793be193bc613/include/herokuish.bash#L65-L68). (docs need to be updated) `herokuish` also attempts to ensure the process can access all the files in `/app` [here](https://github.com/gliderlabs/herokuish/blob/8ca51f4f408c8239ab1bf0f342e793be193bc613/include/procfile.bash#L88-L92) based on what we determined the correct user should be.

Therefore, when you attempted to execute `herokuish procfile start web` and the owner of `/app` did not line up with `/etc/passwd`, the `usermod` cmd failed (silently).

In any case, I think the following patch to your referenced repo will fix your issue:
```
diff --git a/runner/run.sh b/runner/run.sh
index 917cc85..cac31b8 100755
--- a/runner/run.sh
+++ b/runner/run.sh
@@ -7,6 +7,7 @@ BUILD_URL=$2
 wget $BUILD_URL -O /tmp/app.tar
 mkdir /app
 tar -xf /tmp/app.tar -C /
+chown -R herokuishuser /app

 herokuish procfile start $PROC_TYPE &
```

Alternatively, you can invoke your runner with `--env USER=herokuishuser`, thusly:
```
$ docker run --env USER=herokuishuser -it mangoraft/cedar:runner /run.sh web https://play.minio.io:9000/herokuish/build.tar
```

**Comment by FLYBYME** [comment]
@michaelshobbs  Perfect gold star for you.

I do think that it should not fail silently and should at least notify the user of any issue.

**Comment by michaelshobbs** [comment]
Glad we worked it out. Agreed it shouldn't fail silently. PRs are welcomed. 😄
