### ISSUE TITLE
failing installation behind proxy: wrong docker argument ?

### ISSUE THREAD

**Issue by Finkes** [gliderlabs/herokuish#240]
Description of problem:

I try to install dokku on Ubuntu behind a corporate proxy following the official documentation. The installation fails during the installation of herokuish with following output: 

```
Adding proxy settings to docker build: --build-args http_proxy=<PROXY_ADDRESS> --build-args https_proxy=<PROXY_ADDRESS>
unknown flag: --build-args
See 'docker build --help'.
dpkg: error processing package herokuish (--configure):
 subprocess installed post-installation script returned error exit status 125
```

I think this is a very simple issue, because the official docker docs says the flag is called **--build-arg** instead of **--build-args**! see : https://docs.docker.com/engine/reference/commandline/build/#set-build-time-variables---build-arg

Could you check this?

**Comment by Finkes** [comment]
https://github.com/dokku/dokku/issues/2665

**Comment by michaelshobbs** [comment]
Closing as this is an issue with dokku installation packaging and there's already an issue open to track it.
