### ISSUE TITLE
Logs are not visible, if Procfile has a shell script #2667

### ISSUE THREAD

**Issue by nikhil-bhandari** [gliderlabs/herokuish#243]
Hey,

If my Procfile is like:

```
web: sh sh/warmup.sh & java -jar server/webapp-runner.jar --port $PORT target/*.war
```

I don't see application logs, but they start working if I run it like this

```
web: java -jar server/webapp-runner.jar --port $PORT target/*.war
```

The Idea is to run a warm up script(wampup.sh) that hits the web process before it starts receiving requests.

More on that here: https://devcenter.heroku.com/articles/warming-up-a-java-process

I first thought that this is something related to dokku but then I tried a lot of scenarios and it seems that its related to herokuish.

More details here: https://github.com/dokku/dokku/issues/2667

So I have tried running sample java and node js apps in:

1. Dokku
2. herokuish - (FROM gliderlabs/herokuish:latest)
3. and just docker

But the problem comes up only in 1 and 2.

Any suggestions on fixing this?

**Comment by josegonzalez** [comment]
I think this has to do with the background process. Using a shell script in general works fine I think.

**Comment by michaelshobbs** [comment]
I don't think this will work as we use `exec` to kick off the process in the container. My suggestion would be to use a [custom zero downtime check](http://dokku.viewdocs.io/dokku/deployment/zero-downtime-deploys/#customizing-checks) or a [post-deploy deployment task](http://dokku.viewdocs.io/dokku/advanced-usage/deployment-tasks/#deployment-tasks) to hit your process

**Comment by nikhil-bhandari** [comment]
@josegonzalez Also mentioned about checks, but my production app is on heroku and I still need the script in my Procfile.

If its not possible to fix this, I'll try generating Procfile in the buildpack based on environment. I'm not sure if that's possible, but I'll try.

Thanks for your help. :+1:
