### ISSUE TITLE
Support for Heroku-16 Docker image

### ISSUE THREAD

**Issue by eillarra** [gliderlabs/herokuish#256]
Any plans for supporting the Ubuntu 16.04 based [heroku-16](https://hub.docker.com/r/heroku/heroku/) Docker image in the near future?
It will be a great addition, considering that the resulting Docker images will be a third of the size...

[label:enhancement]

**Comment by josegonzalez** [comment]
The stack just hit stable 2 days ago. We will be sure to add support for it, but for now we'll be sticking to the cedar stack.

Thanks for the issue.

**Comment by chrisnicola** [comment]
Is there a sense of when this will be looked at? Also, is this something that is as simple as forking and changing the image references here from `heroku/cedar:14` to `heroku/heroku:16`? Or is there a bit more to it?

**Comment by josegonzalez** [comment]
@chrisnicola it'll be looked at when someone has time. Would you like to start working on it?

**Comment by chrisnicola** [comment]
I would be happy to give it some of my time, but I'm new to Dokku, hence my initial questions. I'll get a bit deeper into Dokku itself before making an attempt.

**Comment by krautnerds** [comment]
@josegonzalez We would also love to see this feature - what parts have to be tested after setting the base image to heroku16? Is the test coverage already big enough in this project?

Also to be discussed: Should there be a choice between cedar14 and heroku16?

**Comment by pynixwang** [comment]
1. ssh into your server
2. clone this repo
3. patch Dockerfile
4. build docker image
5. rebuild app

Dockerfile patch

change `heroku/cedar:14` to `heroku/heroku:16`
append `RUN apt-get update && apt-get install -y daemontools` to end

Build docker image
`docker build -t gliderlabs/herokuish:latest .`

Now you use heroku16 and app image only 600 MB.

**Comment by pynixwang** [comment]
<img width="703" alt="screen shot 2017-09-15 at 11 46 32 pm" src="https://user-images.githubusercontent.com/1189879/30491535-2aa2f544-9a70-11e7-83b4-b500ba7aca7b.png">

image for proof.

**Comment by chrisnicola** [comment]
Perhaps a bit off topic, but for those looking at this I highly recommend looking into deploying with just a Dockerfile instead of using heroku images. It is not very difficult to migrate to this from buildpacks and is much more flexible.

**Comment by josegonzalez** [comment]
Copying a comment from @michaelshobbs in #294, with a minor change:

> In dokku, dockerfile deploys are always an option. If speed/size/finer grain control of deployment are of any concern to a particular user, I always recommend dockerfile-based deployments.
>
> In the context of this [issue] however, the entire point of herokuish is to provide heroku buildpack compatibility. Thus, I think this project does in fact need to maintain that functionality.

<small>I changed issue to pr</small>
