### ISSUE TITLE
NodeJS app restarts on failure, but cannot be curled

### ISSUE THREAD

**Issue by aleclarson** [gliderlabs/herokuish#292]
I'm testing a NodeJS app that uses `herokuish` and everything works as expected after `git push` or `dokku ps:restart`. I'm testing what happens when the server crashes due to an unhandled error. The restart policy is set to `on-failure:10` and works as expected, with the server being successfully restarted. The problem is when I try to `curl` the server after it's been restarted (and after the previous container has been removed). This is what I get:

```
<!DOCTYPE html>
<html>
<head>
  <title>We're sorry, but something went wrong (500)</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <style>
  body {
    background-color: #6CABF7;
    color: #fff;
    text-align: center;
    font-family: arial, sans-serif;
    margin: 0;
  }
  div {
    position:absolute;
    top: 50%;
    left: 50%;
    transform: translateX(-50%) translateY(-50%);
  }
  p {
    color: #eee;
  }
  </style>
</head>

<body>
  <div>
    <h1>We're sorry, but something went wrong.</h1>
    <p>If you are the application owner check the logs for more information.</p>
  </div>
</body>
</html>
```

So I'm looking for a solution to avoid this happening.

The current workaround is to manually `dokku ps:restart app` but I **need** it to just work after restarting, to avoid any downtime.

I noticed the hostname changes (after the restart) from `172.17.0.6` to `172.17.0.5` (the port doesn't change). Could that be the issue?

If you need more information, let me know. Thanks!

**Comment by josegonzalez** [comment]
This doesn't have anything to do with herokuish, but is a change in how docker works under dokku. Please see https://github.com/dokku/dokku/pull/2736 for more details.

**Comment by aleclarson** [comment]
@josegonzalez So once that PR is merged, everything will work as expected?

**Comment by josegonzalez** [comment]
@aleclarson Potentially, but I advise you to read through that pull request and the related issue for more details.

**Comment by aleclarson** [comment]
@josegonzalez Wow, the fix has been in progress for a whole year. What are the recommended Docker and Dokku versions to roll back to while I wait?

**Comment by josegonzalez** [comment]
@aleclarson please either comment on the issue/pull request in Dokku or ask in our online chat.
