### ISSUE TITLE
Should an imported slug be able to run standalone?

### ISSUE THREAD

**Issue by sam3d** [gliderlabs/herokuish#295]
That is to say, even if I've done a `/build` in a container and _then_ exported the slug, when I import it back into a separate herokuish container, should I still need to run `/build` again before I can run `/start web`? Or is something weird going on?

**Comment by sam3d** [comment]
Yeah this seems like odd behaviour. I have a node.js application that builds successfully inside of a herokuish container using `/build`. I then generate and export a slug:

```
$ docker run -d node-app-image /bin/herokuish slug export
-----> Compiled slug size is 14M
```

Then I start a new container, copy the slug to `/tmp/slug.tgz` and run `herokuish slug import < /tmp/slug.tgz` which brings the node files into the `/app` directory correctly (including the `node_modules` that would not have built otherwise), but when I try to start it with `/start web` I get no output:

```
root@9d52474535c0:/# /start web
root@9d52474535c0:/#
```

Instead, inside the container _after_ the slug import if I run `/build` it seems to recognise and use the prebuilt node dependencies, but it seems to want to re-download the node binaries.

```
-----> Node.js app detected

-----> Creating runtime environment

       NPM_CONFIG_LOGLEVEL=error
       NPM_CONFIG_PRODUCTION=true
       NODE_VERBOSE=false
       NODE_ENV=production
       NODE_MODULES_CACHE=true

-----> Installing binaries
       engines.node (package.json):  unspecified
       engines.npm (package.json):   unspecified (use default)

       Resolving node version 6.x via semver.io...
       Downloading and installing node 6.11.4...
       Using default npm version: 3.10.10

-----> Restoring cache
       Skipping cache restore (new runtime signature)

-----> Building dependencies
       Prebuild detected (node_modules already exists)
       Rebuilding any native modules
       express@4.16.2 /tmp/build/node_modules/express
                      ...
       vary@1.1.2 /tmp/build/node_modules/vary
       Installing any new modules (package.json)

-----> Caching build
       Clearing previous node cache
       Saving 2 cacheDirectories (default):
       - node_modules
       - bower_components (nothing to cache)

-----> Build succeeded!
-----> Discovering process types
       Procfile declares types -> web, worker
```

Is this expected behaviour?

**Comment by josegonzalez** [comment]
What was the exit status of `/start web`?

**Comment by sam3d** [comment]
Weirdly, there wasn't one. There's no output at all.

```
root@d96b2715786d:/# /start web $?
cat: /app/Procfile: No such file or directory
root@d96b2715786d:/# herokuish slug import < /tmp/slug.tgz
root@d96b2715786d:/# /start web
root@d96b2715786d:/# /start web $?
root@d96b2715786d:/#
```

**Comment by michaelshobbs** [comment]
To be honest, I don't use the slug feature. However, `/build` executes the buildpack's `compile`/`release` hooks and in this case, the node buildpack always downloads the node binaries. So *that* is expected behavior. 

Regarding your original question about slug itself, I'm not 100% sure how this would work with interpreted languages as I don't think we tar up anything outside of the app dir. That brings up another question, though, of where does the buildpack download it's deps to....

**Comment by sam3d** [comment]
Thank you for confirming that this is the intended behaviour. I'll check the buildpack and see if I can find out where it puts its dependencies.

In the meantime, I need to distribute this application over a docker swarm. I was going to distribute the slugs and then run them through a local instance of herokuish on each node, but I didn't realise there would be computational and network requirements for re-downloading these. I'll go with the probably now-easier way of creating a swarm-scoped local registry and putting each generated herokuish image in there.

Thank you! :)

**Comment by sam3d** [comment]
Okay yeah actually this distribution mechanism, it's easier to just distribute the application images and use them in a similar way to dokku. Thanks again for the confirmation!
