### ISSUE TITLE
Incorrect parsing of Procfile commands

### ISSUE THREAD

**Issue by Benjamin-Dobell** [gliderlabs/herokuish#30]
Procfile command parsing is using ```eval``` (https://github.com/gliderlabs/herokuish/blame/41aeaed24f778bf9582f9112e2cf79418f7fc8cc/include/procfile.bash#L21):
```
unprivileged /bin/bash -c "$(eval echo $@)"
```

Doing ```$(eval <blah>)``` doesn't serve a purpose, it just breaks commands that include quotes.

my-quotes.sh:
```
#!/bin/sh
echo "echo \$@ = $(echo $@)"
echo "eval echo \$@ = $(eval echo $@)"
```

Execution example:
```
./my-quotes.sh sh -c \"echo \$PORT\"
echo $@ = sh -c "echo $PORT"
eval echo $@ = sh -c echo 10
```

Note that the quotes have been dropped. Also, variable expansion has taken place, which we *do* want in Herokuish. However, the variable expansion will be performed by ```/bin/bash -c``` on the same line in ```procfile.bash```.

**Comment by Benjamin-Dobell** [comment]
Now that I'm definitely using the latest buildstep I can confirm his pull request is *not* necessary using the latest buildstep - it's only "necessary" if you're using an old buildstep with the latest dokku-logging-supervisord.

Technically this change should have no real impact on execution, but the Herokuish bug means that this patch does not work with the current buildstep, so I'm closing this issue.

**Comment by michaelshobbs** [comment]
Can you confirm this is still an issue?
