### ISSUE TITLE
Incorrect NODE_ENV set when running herokuish buildpack test

### ISSUE THREAD

**Issue by migueloller** [gliderlabs/herokuish#309]
After running `herokuish buildpack test`, the following is displayed:

```
-----> Node.js app detected

-----> Creating runtime environment
       
       NPM_CONFIG_LOGLEVEL=error
       NPM_CONFIG_PRODUCTION=false
       NODE_VERBOSE=false
       NODE_ENV=test
       NODE_MODULES_CACHE=true
```

When my tests run, though, `NODE_ENV` is actually set to `production` and not `test`.

**Comment by josegonzalez** [comment]
Thats not actually something we handle, but is set by the underlying nodejs buildpack.

**Comment by migueloller** [comment]
Ahh, I see. I’ll ipen an issue there. Thanks for the prompt reply!
