### ISSUE TITLE
buildpack install doesn't checkout git submodules

### ISSUE THREAD

**Issue by nusnewob** [gliderlabs/herokuish#311]
When installing buildpacks from git repos, it doesn't checkout any submodules in the git repos, which could result buildpacks dependent source code missing. To checkout submodules should be included as standard clone behaviour.

**Comment by josegonzalez** [comment]
Do buildpacks on heroku have submodules, and do they check those out? I don't think they do, but I could be wrong.

**Comment by natanrolnik** [comment]
Hey @josegonzalez!
So I'm having the same problem. I'm trying to use [this buildpack](https://github.com/vapor-community/heroku-buildpack) in Dokku. In Heroku it works fine, `swiftenv` is installed correctly and deploy succeeds. However, in Dokku, I get the following error after the buildpack is selected:

```
remote: + [[ -----> Installing swiftenv == --* ]]
----->' Installing swiftenv
-----> Installing swiftenv
remote: + read -r line
remote: fatal: Not a git repository (or any of the parent directories): .git
```

This happens in the following lines: https://github.com/vapor-community/heroku-buildpack/blob/26ec0dee319e32897a8f9b4ea1dbf5e79eca9d71/bin/steps/swiftenv#L1-L4

I'll be happy to provide more info as needed. In case you want to try a Swift app, [Vapor](https://docs.vapor.codes/3.0/install/macos/) is a good choice.

**Comment by josegonzalez** [comment]
@natanrolnik can you provide trace output for the build?

**Comment by natanrolnik** [comment]
Sure, here it is:
https://gist.github.com/natanrolnik/8e6780dfef82f322ca8846e313d9b6bf

**Comment by josegonzalez** [comment]
So we delete the .git directory during buildack installation. Not sure why, @progrium do you remember why this was the case? It’s basically the first commit in herokuish here 
https://github.com/gliderlabs/herokuish/commit/7fad9743ce031cdd0920617d9b6b1cf63f63c23e .

**Comment by natanrolnik** [comment]
@josegonzalez can you imagine why this `.git` removal is there? How could we test if things keep working if we remove this line?

**Comment by josegonzalez** [comment]
No I cannot imagine, thats why I asked Jeff to comment.

**Comment by michaelshobbs** [comment]
https://github.com/gliderlabs/herokuish/pull/378#issuecomment-414150888

[dokku](https://github.com/dokku/dokku) handles this prior to pushing the app into the herokuish container. i recommend following that same pattern here if you do not wish to utilize dokku.

**Comment by josegonzalez** [comment]
I think this is for when the buildpack - for whatever reason - has submodules. Those seem to work fine on heroku, and I think they delete them when they are building slugs. Not really sure when _that_ happens - maybe a cleanup step after the buildpacks are executed?

**Comment by michaelshobbs** [comment]
closing as PR is merged
