### ISSUE TITLE
Multiple commands is not supported in Procfile

### ISSUE THREAD

**Issue by jxltom** [gliderlabs/herokuish#326]
```command_a; command_b``` or ```command_a && command_b``` format command in Procfile is not supported.

This is because ```eval echo "$@``` in ```exec setuidgid "$unprivileged_user" $(eval echo "$@")``` 
 https://github.com/gliderlabs/herokuish/blob/1bf53652e0e3829924265c3db12dc8d072939363/include/procfile.bash#L55 will strip the multiple commands

**Comment by jxltom** [comment]
Currently I can only run multiple command by ```web $(command_a; command_b)```

**Comment by michaelshobbs** [comment]
That is correct. I also use a `Makefile` to achieve executing multiple commands where absolutely necessary.

**Comment by jxltom** [comment]
@michaelshobbs But in heroku, ```web: command_a; command_b``` is supported. Why not herokuish support multiple commands like that since herokuish is trying to emulating heroku?

**Comment by josegonzalez** [comment]
Because its hard to do it and not a common pattern. I would actually say that such a Procfile is wrong, but since there isn't a Procfile standard out there, _shrug_.

If you would like to submit a pull request to change this (with tests!) feel more than free to do so. I'd be happy to review :)

**Comment by jxltom** [comment]
@josegonzalez 

OK. Thanks for clarifying my doubt.

**Comment by schittler** [comment]
I'd like to note with the backref above, that this is expected behavior in a lot of apps targeting heroku out of the box, like for instance https://github.com/tootsuite/mastodon

**Comment by josegonzalez** [comment]
If you'd like to make a pull request implementing this functionality, that would be great. Otherwise, I don't think it's worth the effort.
