### ISSUE TITLE
Update AUR package

### ISSUE THREAD

**Issue by Tyilo** [gliderlabs/herokuish#348]
The package on AUR is for version 0.3.27, but the latest release of herokuish is 0.4.0.

Please update it: https://aur.archlinux.org/packages/herokuish/

@josegonzalez seems to be the maintainer

**Comment by ayr-ton** [comment]
This is already solved.
The current version is 0.5.3-1

Feel free to report the outdated package inside AUR itself at "Package Actions -> Flag package out-of-date"
