### ISSUE TITLE
Meteor not found

### ISSUE THREAD

**Issue by wernight** [gliderlabs/herokuish#376]
Running GitLab Auto DevOps on a Meteor project fails at test phase:

```
$ # Auto DevOps variables and functions # collapsed multi-line command
$ setup_test_db
$ cp -R . /tmp/app
$ /bin/herokuish buildpack test
-----> Node.js app detected
...
-----> Build succeeded!

> example@ test /app
> meteor test --once --driver-package meteortesting:mocha

sh: 1: meteor: not found
npm ERR! Test failed.  See above for more details.
ERROR: Job failed: error executing remote command: command terminated with non-zero exit code: Error executing in Docker Container: 1
```

Running GitLab 11.0.3-ce with GitLab CI 11.0 Alpine on Kubernetes (however most of that shouldn't matter): [Auto DevOps gitlab-ci.yaml line that fails](https://gitlab.com/gitlab-org/gitlab-ci-yml/blob/master/Auto-DevOps.gitlab-ci.yml#L88): Running `/bin/herokuish buildpack test` in `image: gliderlabs/herokuish:latest`.

I see that some tools may be added at runtime but seems not Meteor, and meteor isn't by default in this image.

**Comment by josegonzalez** [comment]
Are you installing meteor? If not, that'll be your issue.

**Comment by wernight** [comment]
How would I? First GitLab Auto DevOps doesn't do allow installing but I think this image could automatically handle that, i.e. install necessary tools automatically. IMO that's why GitLab is using this image for auto devops.

**Comment by josegonzalez** [comment]
If you do not have meteor in your nodejs dependencies, then how would it know to install meteor? We simply do what would be done on heroku, nothing more. And no, we're not going to modify the underlying buildpacks to add meteor.

Can you gist the entire build output? You truncated all the parts that would indicate whether or not meteor was installed.

**Comment by josegonzalez** [comment]
Closing as there hasn't been a response in a while.
