### ISSUE TITLE
Buildpack name and order

### ISSUE THREAD

**Issue by stuartpb** [gliderlabs/herokuish#4]
I'm... not wild about `heroku-buildpack-multi` being arbitrarily special-cased in the buildpack loop (https://github.com/gliderlabs/herokuish/blob/master/include/buildpack.bash#L76). I could well have a meta-buildpack similar in nature that I'd want to run before other buildpacks, or even before buildpack-multi.

I'd rather the `build` command take an optional list of buildpacks to execute (defaulting to using `ls $BUILDPACKS_DIR`, optionally with the special case for hoisting heroku-buildpack-multi). This is how I'm planning to handle buildpack execution order in Plushu: right now, each buildpack is installed with a numeric prefix on its directory name (which is hacky, fragile and hard to work with, which is why I'm planning to switch to the separate-list approach). Anyway, with that naming scheme, this `heroku-buildpack-multi` special case *wouldn't even trigger*.

This also lets platforms smoothly disable/switch out buildpacks for different build scenarios (maybe one user is on the "velvet deluxe Groovy build system" plan while one is on the "barebones cot-on-the-floor cheapskate Maven runner" plan).

**Comment by stuartpb** [comment]
> I'm pragmatic enough to let this continue to exist, though, without a good alternative.

*With* a good alternative, though, this should be removed, at least as an inherent/implicit part of the code (what if I have a directory of meta-buildpacks where heroku-buildpack-multi should be executed *last*?)

> I think using the order of listing is the best idea.

This is how Plushu's buildpack system implicitly works right now (each buildpack gets a numeric prefix), and it's a pain (plushu/plushu-buildpacks#1). I'm moving toward just maintaining a list of buildpacks to install.

Anyway, if you don't like having to main this list, but you still want a way to hoist heroku-buildpack-multi to the top, this is what I suggest:

- Have an option to provide an explicit list of buildpacks: if not provided, the list will be generated from all the buildpacks (and sorted ASCIIbetically, so you can do numeric prefixes if you want).
- Have another option, after getting the list (either from a file or from `ls`), to *hoist* or *drop* specific entries (if they're present) in the list (so any platform who wants heroku-buildpack-multi to come before the rest of the bag would run with `herokuish build --hoist heroku-buildpack-multi`).

I'll look into providing a patch for this later.

**Comment by progrium** [comment]
The primary function of a list is to provide sort order, but as far as I
know from Deis/Flynn/Dokku, that only reason that matters is for the
special case of multi. So it would seem perhaps too though through to
provide a general solution for something that's not actually that important
(sorting *all* the buildpacks).

The solution I'm more in favor of doing on top of ascii sort is
configurable hoisting. Dropping when there is a good use case (do you have
them yet?). But then we get into the debate of option vs env var. ;)

On Tue, Jan 6, 2015 at 5:37 PM, Stuart P. Bentley <notifications@github.com>
wrote:

> I'm pragmatic enough to let this continue to exist, though, without a good
> alternative.
>
> *With* a good alternative, though, this should be removed, at least as an
> inherent/implicit part of the code (what if I have a directory of
> meta-buildpacks where heroku-buildpack-multi should be executed *last*?)
>
> I think using the order of listing is the best idea.
>
> This is how Plushu's buildpack system implicitly works right now (each
> buildpack gets a numeric prefix), and it's a pain (
> plushu/plushu-buildpacks#1
> <https://github.com/plushu/plushu-buildpacks/issues/1>). I'm moving
> toward just maintaining a list of buildpacks to install.
>
> Anyway, if you don't like having to main this list, but you still want a
> way to hoist heroku-buildpack-multi to the top, this is what I suggest:
>
>    - Have an option to provide an explicit list of buildpacks: if not
>    provided, the list will be generated from all the buildpacks (and sorted
>    ASCIIbetically, so you can do numeric prefixes if you want).
>    - Have another option, after getting the list (either from a file or
>    from ls), to *hoist* or *drop* specific entries (if they're present)
>    in the list (so any platform who wants heroku-buildpack-multi to come
>    before the rest of the bag would run with herokuish build --hoist
>    heroku-buildpack-multi).
>
> I'll look into providing a patch for this later.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gliderlabs/herokuish/issues/4#issuecomment-68966270>.
>



-- 
Jeff Lindsay
http://progrium.com

**Comment by stuartpb** [comment]
> Dropping when there is a good use case (do you have them yet?)

This is just hypothetical, but you could have a final fallthrough buildpack that only triggers when all other buildpack tests fail with a test that always returns `true` (for instance, one that treats the files as a static / Jekyll site).

**Comment by progrium** [comment]
I'm confident that would create more confusion for any user of the system
than help. Either the platform supports your app and is detected by a
buildpack, or not. If it treats all unsupported apps as if they're
something they probably aren't, that's not good for anybody.

On Tue, Jan 6, 2015 at 9:12 PM, Stuart P. Bentley <notifications@github.com>
wrote:

> Dropping when there is a good use case (do you have them yet?)
>
> This is just hypothetical, but you could have a final fallthrough
> buildpack that only triggers when all other buildpack tests fail with a
> test that always returns true (for instance, one that treats the files as
> a static / Jekyll site).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gliderlabs/herokuish/issues/4#issuecomment-68979822>.
>



-- 
Jeff Lindsay
http://progrium.com

**Comment by michaelshobbs** [comment]
Closing as there's nothing seemingly actionable here.
