### ISSUE TITLE
Update PHP Buildpack

### ISSUE THREAD

**Issue by kaneboojer** [gliderlabs/herokuish#400]
Started seeing this error yesterday and noticed it seems to coincide with the v148 PHP buildpack release.

`Status: Downloaded newer image for gliderlabs/herokuish:latest
-----> PHP app detected
-----> Bootstrapping...

! ERROR: Failed to download minimal PHP for bootstrapping!
!
! This is most likely a temporary internal error. If the problem
! persists, make sure that you are not running a custom or forked
! version of the Heroku PHP buildpack which may need updating.`

**Comment by josegonzalez** [comment]
This is happening now. Thanks for the bump.

**Comment by btb-dimitar** [comment]
I've been using PHP 7.1.18 with buildpack v136 for a long time, but now I'm getting this error:

```
-----> Multipack app detected
=====> Downloading Buildpack: https://github.com/heroku/heroku-buildpack-php
=====> Detected Framework: PHP
-----> Bootstrapping...
       
       !     ERROR: Failed to download minimal PHP for bootstrapping.
       Please try again, or contact support if this problem persists.
       
```

I haven't changed anything in my setup. Looking at log files I think this started happening 12 days ago.

The error goes away if I switch to buildpack v148 and PHP 7.1.25

Is there a way to keep using v136 ??

**Comment by josegonzalez** [comment]
No. The buildpacks are managed by heroku. They change urls and rebuild stuff constantly. As such, using an old version won't work for very long.
