### ISSUE TITLE
Implicit Procfile support

### ISSUE THREAD

**Issue by matthewmueller** [gliderlabs/herokuish#401]
I'm not sure how dokku does this, but for node.js apps the Procfile is optional. If there's no Procfile, the command is implied from the `package.json`'s `scripts.start` key.

I think dokku is somehow calling this binary: https://github.com/heroku/heroku-buildpack-nodejs/blob/master/bin/release

I noticed that's not present in herokuish, is that intentional or just not supported yet?

**Comment by matthewmueller** [comment]
Oh! That's interesting. I don't think something is broken then, I'm probably just misunderstanding. 

I'm basically looking to emulate how dokku does builds locally. I was using `herokuish buildpack build` (which looks like it calls `buildpack execute`), until I realized that it doesn't call your tests.

Then I started using `herokuish buildpack tests` because it says "Build and run tests for an application using installed buildpacks", so I figured that it did everything in build as well as running the tests.

How does dokku do this? It seems like if I called `herokuish buildpack test && herokuish buildpack build` it would build twice.

**Comment by josegonzalez** [comment]
We don't run the tests within the built application. We just run build, [like so](https://github.com/dokku/dokku/blob/master/plugins/common/functions#L470-L487).

As this isn't directly related to a bug or feature, I'd encourage you to jump onto the [gliderlabs slack](https://slack.gliderlabs.com/) with further questions. We can sort them out there and then get anything documented/changed as necessary :)

**Comment by matthewmueller** [comment]
Thanks buddy, I really appreciate the help! 

I'll give it another shot myself and jump on slack if I run into anything. Thanks again!
