### ISSUE TITLE
slug generate gzips from /tmp/app, when it should gzip from /app

### ISSUE THREAD

**Issue by matthewmueller** [gliderlabs/herokuish#402]
Steps to reproduce:

### 1. Use a simple node app, I found this one from the examples or maybe the tests

**server.js**

```js
var express = require('express');
var app = express();

app.get('/', function(req, res){
  res.send("nodejs-express\n");
});

/* Use PORT environment variable if it exists */
var port = process.env.PORT || 5000;
server = app.listen(port);

process.on( "SIGINT", function() {
  console.log('CLOSING [SIGINT]');
  process.exit();
} );

process.on( "SIGTERM", function() {
  console.log('CLOSING [SIGTERM]');
  process.exit();
} );

console.log('Server listening on port %d in %s mode', server.address().port, app.settings.env);
```

**package.json**

```json
{
  "name": "example-nodejs-express",
  "version": "0.0.1",
  "scripts": {
    "start": "node server.js",
    "test": "mocha"
  },
  "engines": {
    "node": "8.14.1",
    "yarn": "1.13.0"
  },
  "dependencies": {
    "express": "3.1.x"
  },
  "devDependencies": {
    "mocha": "*"
  }
}
```

### 2. Now you can run:

```
docker run -ti -e NODE_ENV=production --rm \
  -v ${PWD}:/tmp/app:ro \
  -v ${PWD}/release:/tmp/release \
  -v ${PWD}/cache:/tmp/cache \
  gliderlabs/herokuish:latest bash -c '/bin/herokuish buildpack test && \
  /bin/herokuish slug generate && \
  /bin/herokuish slug export > releases/release.tar.gz'
```

This will build and test the app, then generate the slug, then export it to the release volume. If you open that releases volume, you'll notice that it's just using your pre-built app, the one at `/tmp/app` and not the built app at `/app`.

**Comment by matthewmueller** [comment]
Alrighty, I found the offending line: https://github.com/gliderlabs/herokuish/blob/783f11bd80c714ce53c607097ffba1778733e17c/include/herokuish.bash#L126-L128

```bash
if [[ -d "$import_path" ]] && [[ -n "$(ls -A "$import_path")" ]]; then
	rm -rf "$app_path" && cp -r "$import_path" "$app_path"
fi
```

Basically, if `/tmp/app` exists, remove `/app` and replace it with `/tmp/app`. This is a bit unfortunate when you're building locally because it's basically trying to delete the source files.  Fortunately, if you do readonly on the volume, nothing happens.

Can this be removed?

**Comment by josegonzalez** [comment]
That seems like a reasonable solution @matthewmueller, would you be interested in making a pull request?
