### ISSUE TITLE
Run scrips in .profile(.d) during container startup

### ISSUE THREAD

**Issue by MSchmidt** [gliderlabs/herokuish#450]
Would be great if herokuish started a bash shell during startup of a container just like Heroku does: https://devcenter.heroku.com/articles/dynos#the-profile-file

**Comment by josegonzalez** [comment]
Where is `$HOME` in this case? I'm assuming `/app`.

I also wonder how this is impacted by Buildpacks V3 (asking in the chat there now).

**Comment by MSchmidt** [comment]
That's correct. It's `/app` and already works when entering the container shell manually.

**Comment by josegonzalez** [comment]
Okay, seems this is part of the v3 spec.

This should _already_ happen [here](https://github.com/gliderlabs/herokuish/blob/master/include/procfile.bash#L53).

Do you have an example where it isn't happening?

**Comment by josegonzalez** [comment]
If this is with Dokku, you may wish to join us on our slack or irc channel to ask for support, as a GitHub issue isn't the best place to conduct that sort of conversation.

Given that this functionality appears to work, I'm going to close this. If it happens to be an issue with Herokuish, we can re-open at a later date.
