### ISSUE TITLE
Lumen/Laravel issue when using Herokuish

### ISSUE THREAD

**Issue by MisterCoder** [gliderlabs/herokuish#481]
This is discussed in https://github.com/gliderlabs/herokuish/issues/188 but now it is also causing issues with Lumen/Laravel.

If you have a .env file in your Lumen/Laravel app it is read in via Herokuish. The DotEnv PHP package that Lumen/Laravel uses will not override existing ENV values so this causes nested values to fail.

Nested values are formatted like...

MY_VALUE=1234
MY_NESTED_VALUE=${MY_VALUE}

Outside of Herokuish MY_NESTED_VALUE is set to 1234 correctly but inside the Herokuish environment is it left empty.

A solution would be to allow the .env filename to be customised but ultimately this conflict would still exist.

**Comment by MisterCoder** [comment]
I think I have a better solution. It looks like the .env parsing in Herokuish can be amended to resolve the issue and not break existing uses.

I'm going to experiment now.

**Comment by MisterCoder** [comment]
Added a PR https://github.com/gliderlabs/herokuish/pull/482

**Comment by MisterCoder** [comment]
Not sure if I'm on the right track with this but it looks like grouping the exports and running them via eval() *MAY* be causing them to be set as blank?

**Comment by MisterCoder** [comment]
The tests I added seem to have passed in CI so it looks like I'm on the wrong track here.

```
=== RUN T_envfile-parse
--- PASS T_envfile-parse (0s)
```

**Comment by MisterCoder** [comment]
Still having issues here.

When doing "buildpack test" with my lumen app the ENV vars based on other ENV vars (See above) are blank strings. I have confirmed this via var_dump()'ing $_ENV at the top of the PHPUnit bin file.

This only happens when using buildpack test so could be limited to the buildpack but I can't find whatever is setting the ENV value within it.

**Comment by MisterCoder** [comment]
Dumping the `env` at the top of each buildpack `compile`, `test-compile` and `test` shows the ENV values have already been set to blank values.

**Comment by josegonzalez** [comment]
Closing as we weren't able to prove this was a bug in Herokuish (with the above test) and there hasn't been any follow-up in a while (note: I personally don't have time to setup a test laravel environment to try and reproduce this).
