### ISSUE TITLE
Feature request: Cloud Native Buildpack support

### ISSUE THREAD

**Issue by brandonkal** [gliderlabs/herokuish#498]
Support CNB so downstream projects can benefit.
Ref: https://buildpacks.io/

**Comment by josegonzalez** [comment]
I've already discussed this with the CNB folks.

The purpose of this project is to allow folks to emulate the Heroku build/runtime environment. Heroku - amongst others - will be moving to CNB at some point, and already provide a [shim](https://github.com/heroku/cnb-shim) for existing buildpacks in the new system. So in theory, any CNB platform would be able to use that shim + any tooling that supports CNB for buildpack support.

The [pack-cli](https://github.com/buildpack/pack) already provides a way for folks to build and run applications, and analogs for most `herokuish` cli commands - missing are slug generation, which I am inquiring about in the CNB slack channel. Given that:

- pack-cli already exists
- supports existing v2a buildpacks (Heroku Buildpacks)
- is actively maintained by the CNB folks
- can run inside of a container with a socket mounted, similar to how herokuish runs

I think the best course of action is for Herokuish to become unsupported once pack-cli hits a stable release (or at least supports all the functionality Herokuish currently does). Unless others step up to maintain herokuish - unlikely - I don't see this project getting major enhancements/refactors in the foreseeable future. Only general maintenance work (upgrading buildpacks) will be done, and at some point I hope to archive this project in favor of `buildpacks/pack` and the `buildpacks/lifecycle` projects.

While that's a bit unfortunate for folks already using this project, I think that it makes sense long-term for the community. Adding CNB support to Herokuish would be quite a bit of work for little value, especially in terms of the goals of the project.
