### ISSUE TITLE
It could be possible to specify slug_path?

### ISSUE THREAD

**Issue by aledbf** [gliderlabs/herokuish#5]

**Comment by progrium** [comment]
Obviously if there is a use case that makes sense ... can you tell me why?

**Comment by aledbf** [comment]
I want to remove the docker in docker build in deis and if the slug_path is the same it could be a problem to build multiple apps at the same time

**Comment by progrium** [comment]
That sounds like it's asking for trouble. Why not run multiple app builds
in separate containers?

On Sat, Jan 10, 2015 at 12:39 PM, Manuel Alejandro de Brito Fontes <
notifications@github.com> wrote:

> I want to remove the docker in docker build in deis and if the slug_path
> is the same it could be a problem to build multiple apps at the same time
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gliderlabs/herokuish/issues/5#issuecomment-69466683>.
>



-- 
Jeff Lindsay
http://progrium.com
