### ISSUE TITLE
PHP Buildpack Error

### ISSUE THREAD

**Issue by devkokov** [gliderlabs/herokuish#513]
I suddenly started getting this error on all my apps. What's the proper fix other than hardcoding a specific BUILDPACK_URL on all my apps?

Thanks!

-----> Bootstrapping...

 !     ERROR: Failed to download minimal PHP for bootstrapping!
 !     
 !     This is most likely a temporary internal error. If the problem
 !     persists, make sure that you are not running a custom or forked
 !     version of the Heroku PHP buildpack which may need updating.

**Comment by josegonzalez** [comment]
The released a new version for the minimal bootstrap yesterday [here](https://github.com/heroku/heroku-buildpack-php/blame/master/bin/compile#L221). I'm guessing the heroku workflow is to delete the old bootstrap, and this forces people to use the master branch of the php buildpack vs using an older one as time goes on.

I'm releasing a herokuish update today, so we should get the latest version soon.

**Comment by josegonzalez** [comment]
Closed by https://github.com/gliderlabs/herokuish/pull/517
