### ISSUE TITLE
Define a custom base image for docker containers build via herokuish

### ISSUE THREAD

**Issue by steffenrumpf** [gliderlabs/herokuish#522]
Hi,
is there a way to define a custom base image for docker containers which are build via herokuish?

I tried the following but without success: https://devcenter.heroku.com/articles/build-docker-images-heroku-yml

Kind Regards
Steffen

**Comment by josegonzalez** [comment]
@steffenrumpf is this a question for Dokku or for standalone herokuish usage?

**Comment by steffenrumpf** [comment]
@josegonzalez I just want to know if it's possible so yes I guess it's about doku e.g. for npm builds to define my own base image for builds run via herokuish. Basically we use herokuish within GitLab-CI if that helps.

**Comment by josegonzalez** [comment]
If this is for Gitlab's "autodevops" integration, then that has nothing to do with Dokku.

To use a different base image, you'll need to build your own version of herokuish using a custom Dockerfile. We only build herokuish based on Ubuntu 18.04 at the moment, and have no plans to change that at this time.
