### ISSUE TITLE
Run arbitrary commands inside buildpack

### ISSUE THREAD

**Issue by abitrolly** [gliderlabs/herokuish#555]
I need to regenerate `Gemfile.lock` for my project. Heroku buildpack reads Ruby version specifier from `Gemfile` and creates an environment with this version. I'd like run `bundle update` command in that environment. Is that possible?

**Comment by josegonzalez** [comment]
We support whatever the buildpack supports. Why not run `bundle update` locally and commit the updated files?

**Comment by abitrolly** [comment]
@josegonzalez locally I was unable to install the old version of Ruby and dependencies that the project uses.

**Comment by josegonzalez** [comment]
That sounds like an issue with your system, not with the buildpacks included here.

Regardless, a custom buildpack can be used - whether that is from scratch or a fork of an existing one - and you can add any commands necessary to those buildpacks to act against your repository. As this repository is meant to provide a compatibility layer with Heroku's buildpack system, adding non-standard functionality isn't planned.

**Comment by abitrolly** [comment]
@josegonzalez I am using Fedora. There Ruby version that ships with it is not compatible with the legacy code of the project. I thought that `herokuish` could help me to get the necessary development environment for Heroku quickly.
