### ISSUE TITLE
Potentially outdated "latest" version on dockerhub

### ISSUE THREAD

**Issue by betabandido** [gliderlabs/herokuish#607]
Are there any plans to update the latest version published on dockerhub? It appears to not have been updated since May (see attached image).

![image](https://user-images.githubusercontent.com/5481662/95082166-ed7f0200-071a-11eb-8280-15c18937ac9d.png)

**Comment by betabandido** [comment]
@josegonzalez -- I've seen you've been working on drafting recent releases, so I was wondering if you can have a look at this. Gitlab is using the latest docker tag, and as it is now 6 months old, it does not have recent buildpack versions.

**Comment by josegonzalez** [comment]
This has to do with the fact that the binary isn't available just yet in CI when docker hub tries to build it. Not much I can do about that since hub is what triggers the build, not this repo.

I've triggered the build for now and will add this to my release steps.
