### ISSUE TITLE
question: (basic) best practice for using herokuish to create a runnable image

### ISSUE THREAD

**Issue by tony-kerz** [gliderlabs/herokuish#62]
hi,

apologies in advance for beginner question (feel free to redirect me to more appropriate forum).

i have been using [tutum/buildstep](https://github.com/tutumcloud/buildstep) to build a runnable image [like so](https://github.com/tutumcloud/buildstep#usage) as part of a home-grown build pipeline using jenkins, git and a docker runtime platform.

i recently wanted to [use an iojs runtime in a node app](https://devcenter.heroku.com/articles/nodejs-support#specifying-a-node-js-version), and it turns out [that requires a more recent node buildpack](https://github.com/gliderlabs/herokuish/issues/26) than the one baked into the version of `tutum/buildstep` on dockerhub.

trying to gain some background context, i did some research and came across this thread about [preferring herokuish over buildstep](https://github.com/progrium/dokku/issues/1091#issue-66441226).

along those lines, i would like to use herokuish directly without tutum or progrium buildsteps, but i'm not clear on exactly how to accomplish that.

for example would i use:

1. some form of `docker run gliderlabs/herokuish` at the command line, or
2. `FROM gliderlabs/herokuish` with some other commands in a Dockerfile

any guidance or examples would be appreciated

best,
tony.

**Comment by progrium** [comment]
You'd use `docker run`. I suppose the readme doesn't explain this well? I'll need to write better docs for end users.

**Comment by tony-kerz** [comment]
i toyed with `docker run`, but it wasn't clear to me how to get to a built docker image that way.

i was able to get the desired effect with a `Dockerfile` that looks like this:

```
FROM gliderlabs/herokuish

RUN mkdir -p /app
ADD . /app
RUN /build

ENTRYPOINT ["/exec", "node", "/app/my-app.js"]
```

and running:

```
docker build -t me/my-image .
docker run --rm me/my-image
```

(in my case, my app is just a node command-line app)

does that seem like a reasonable approach?

**Comment by progrium** [comment]
Yeah that works alright, too.

On Wed, Aug 12, 2015 at 8:58 AM, tony kerz <notifications@github.com> wrote:

> i toyed with docker run, but it wasn't clear to me how to get to a built
> docker image that way.
>
> i was able to get the desired effect with a Dockerfile that looks like
> this:
>
> FROM gliderlabs/herokuish
>
> RUN mkdir -p /app
> ADD . /app
> RUN /build
>
> ENTRYPOINT ["/exec", "node", "/app/my-app.js"]
>
> and running:
>
> docker build -t me/my-image .
> docker run --rm me/my-image
>
> (in my case, my app is just a node command-line app)
>
> does that seem like a reasonable approach?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gliderlabs/herokuish/issues/62#issuecomment-130314609>
> .
>



-- 
Jeff Lindsay
http://progrium.com

**Comment by msabramo** [comment]
What would the `docker run` approach look like?

**Comment by msabramo** [comment]
```
docker run --rm -v $(pwd):/tmp/app gliderlabs/herokuish /bin/herokuish buildpack build foobar
```

seems to execute without any errors, but where is the new image?

**Comment by Haybu** [comment]
docker run --rm -v $(pwd):/tmp/app gliderlabs/herokuish /bin/herokuish buildpack build foobar

works all good, where is the built image gets saved ?

**Comment by josegonzalez** [comment]
If you do not `docker commit` the change, its simply in the ephemeral container that is running. You can either specify a name `--name` or use `docker commit` to save the image id.

**Comment by joshmanders** [comment]
The built container is the one you run, you added the `--rm` flag to the `run` command, which means after the container exited, to remove it.
