### ISSUE TITLE
Changes not persisted between buildpacks?

### ISSUE THREAD

**Issue by msabramo** [gliderlabs/herokuish#63]
I must be misunderstanding how herokuish works; hopefully someone can explain what's going on here.

In my `.buildpacks`, I specify 2 buildpacks -- the official Heroku python buildpack and a custom one that I am developing for the tox testing tool.

When the python buildpack executes, I can see it install python and pip in `/app/.heroku/python/bin` and then it uses `pip` to install a bunch of packages. Great.

Now the tox buildpack executes and it tries to do `/app/.heroku/python/bin/pip install tox` and it fails, because the whole `/app/.heroku` directory from the previous step is not there.

I added some debugging:

After the end of python buildpack execution:

```
$ hostname
8ab2d0316829

$ ls -al /app
...
       drwxr-xr-x  2 u17823 u17823  4096 Aug 21 13:52 etc
       -rw-r--r--  1 u17823 u17823   278 Aug 21 13:52 .gitignore
       drwxr-xr-x  4 u17823 u17823  4096 Aug 21 13:52 .heroku
       -rw-r--r--  1 u17823 u17823 43093 Aug 21 13:52 junit.xml
       -rw-r--r--  1 u17823 u17823   105 Aug 21 13:52 MANIFEST.in
...
```

At the beginning of tox buildpack execution:

```
$ hostname
8ab2d0316829

$ ls -al /app
...
       drwxr-xr-x  2 u17823 u17823  4096 Aug 21 13:52 etc
       -rw-r--r--  1 u17823 u17823   278 Aug 19 17:49 .gitignore
       -rw-r--r--  1 u17823 u17823 43093 Aug 19 18:02 junit.xml
       -rw-r--r--  1 u17823 u17823   105 Aug 19 17:49 MANIFEST.in
...
```

Note that the `.heroku` directory is missing. I also just noticed that some of the timestamps are different, which is peculiar.

Here's my `Dockerfile`:

```dockerfile
FROM gliderlabs/herokuish

RUN mkdir -p /app
ADD . /app
RUN /build

CMD ["/exec", "pserve", "/app/etc/app.mt3.ini"]
```

Cc: @progrium, @sudarkoff

**Comment by michaelshobbs** [comment]
Not sure how to recreate this issue. Can you confirm it still exists in `0.3.6`?
