### ISSUE TITLE
Log buildpack version

### ISSUE THREAD

**Issue by nerg4l** [gliderlabs/herokuish#634]
Recently on dokku slack someone reported an issue about an ignored version tag in their `.buildpacks` file. The log only contained the following:

```
       Detected buildpacks: multi php
-----> Multipack app detected
=====> Downloading Buildpack: https://github.com/heroku/heroku-buildpack-php.git
=====> Detected Framework: PHP
```

I tested his report but I was not able to reproduce it. However, simply logging the buildpack version could help investigating such issues. Moreover, if herokuish could log the version when using the latest buildpack then compatibility issue could be detected when a new version breaks a build.

**Comment by josegonzalez** [comment]
The log output there comes from the buildpack upstream. There is a log output change that was added but never released, so I asked for a release to be made here: https://github.com/heroku/heroku-buildpack-multi/issues/19

I would recommend PR'ing any changes to the logging to that repo instead, and we'll pick it up once its released.

**Comment by nerg4l** [comment]
Thanks for the info and for opening that ticket.
