### ISSUE TITLE
Add support for .profile bash file per Heroku

### ISSUE THREAD

**Issue by adzap** [gliderlabs/herokuish#644]
Heroku offers a way to run bash commands from the `.profile` file in app root which is executed for all proc types before the proc command itself [https://devcenter.heroku.com/articles/dynos#the-profile-file](https://devcenter.heroku.com/articles/dynos#the-profile-file)

**Comment by josegonzalez** [comment]
Looks like we can add this by adding a source [after this line](https://github.com/gliderlabs/herokuish/blob/master/include/procfile.bash#L111) to the file if it exists. Something like `touch $app_path/.profile && source $app_path/.profile`?

Mind making a PR for that? :)

**Comment by adzap** [comment]
See #651

**Comment by josegonzalez** [comment]
Merged and released in 0.5.26. Thanks for the PR!
