### ISSUE TITLE
Export_env : command not found

### ISSUE THREAD

**Issue by clemh78** [gliderlabs/herokuish#670]
Hello guys,

We have an error when we run herokuish image on offline environment!

This is an example with an java app:

``docker run --rm -v / root / app /: / tmp / app gliderlabs / herokuish: v0.5.27 / bin / herokuish buildpack test``
``-----> Java app detected``
``/ tmp / buildpacks / 05_buildpack-java / bin / test-compile: line 18: export_env: command not found``
``2021/04/02 08:52:33 exit status 127``

We have systematicaly, 'export_env command not found'.

To reproduce this, remove access to internet (with a firewall for exemple, leave port 22 anyway haha).

If you have an idea for resolv this, we would be very happy.

Thanks!

**Comment by josegonzalez** [comment]
It is up to a specific buildpack to support offline functionality. In this case, it's the heroku buildpack that forces [the following url](https://github.com/heroku/heroku-buildpack-java/blob/c7b2d504e803eec586787a3e47f1e1b6ae85edf7/lib/common.sh#L4).

Feel free to ask upstream to make that an env var so you can overwrite it and we'll pull the update in. The python does it like [so](https://github.com/heroku/heroku-buildpack-python/blob/main/bin/compile#L42).
