### ISSUE TITLE
Update ruby buildpack to v228

### ISSUE THREAD

**Issue by jenshenny** [gliderlabs/herokuish#679]
The newest [ruby buildpack](https://github.com/heroku/heroku-buildpack-ruby/releases/tag/v228) release upgrades Bundler to 2.2.21 which introduces fixes to the "dependency confusion vulnerability".

My organization's infrastructure would like to adopt this change asap, would it be possible to update the ruby buildpack to v228 and cut a new release?

**Comment by jchestershopify** [comment]
xref #683

**Comment by jchestershopify** [comment]
@josegonzalez I think we can close this now. Thanks for being so quick!
