### ISSUE TITLE
persistent user AND userid 

### ISSUE THREAD

**Issue by michaelshobbs** [gliderlabs/herokuish#69]
When using herokuish (+dokku) and docker volumes, the randomized user id is less than ideal. Thoughts on allowing a `$USERID` variable to be passed in?

I'm willing to do the work but wanted feedback on the implementation.

**Comment by josegonzalez** [comment]
IIRC dokku-alt did this in their buildstep branch.

**Comment by michaelshobbs** [comment]
I looked through their stuff but didn't see the commit.....

Regardless, are you saying they did the same or implemented differently?

**Comment by progrium** [comment]
Uggghhhhh I remember thinking we had a solution for this but I've forgotten that whole domain since. Or maybe that was just user. Seems like this makes sense.

**Comment by michaelshobbs** [comment]
Currently we just offer a username override (with env var) but that user must exist in the `herokuish` image already. I ended up building my own and then creating [this very simple](https://github.com/expa/dokku-app-user) dokku plugin.

**Comment by josegonzalez** [comment]
@michaelshobbs might be worth doing this as a PR to fix the issue :)

**Comment by michaelshobbs** [comment]
I haven't come up with a general implementation yet. However, would it be out of reason to create a default user in the image and document its existence and how to use it? (i.e. `$USER`)

**Comment by josegonzalez** [comment]
That seems like a reasonable idea to me.

**Comment by michaelshobbs** [comment]
added in addfa60720699357c1f7d931f481dc0c2a1eccde
