### ISSUE TITLE
Errors in post-install scripts

### ISSUE THREAD

**Issue by schmijos** [gliderlabs/herokuish#692]
The last two lines in the post-install script cause errors if no dangling images are present:

```
Error response from daemon: invalid reference format: repository name must be lowercase
Error response from daemon: conflict: unable to delete be1b644615c9 (must be forced) - image is referenced in multiple repositories
```

Source: https://github.com/gliderlabs/herokuish/blob/master/contrib/post-install#L19-L23

**Comment by henningjensen** [comment]
Got the same problem. 
Have submitted a new pull request with a fix for this. 
#815 https://github.com/gliderlabs/herokuish/pull/815

**Comment by josegonzalez** [comment]
This was fixed.
