### ISSUE TITLE
Question: Can I use the Heroku-22 stack already?

### ISSUE THREAD

**Issue by tadeoos** [gliderlabs/herokuish#790]
Hey,
Thanks a lot for building and maintaining this!

I'm a bit confused about the stack versions. The readme of this repo says:
>The goal is to be the definitive, well maintained and heavily tested Heroku emulation utility shared by all. It is based on the [Heroku:18 and Heroku:20 system images](https://github.com/heroku/stack-images). Together they form a toolkit for achieving Heroku compatibility.

The linked page lists the heroku-22 images with a status "suggested". I couldn't find any docs on how the herokuish images are related to the official images — if an image in the heroku repo exists does this mean I can automatically use `gliderlabs/herokuish:latest-22` or is there a need for a new version of the herokuish package? Is there some repository/command that lists all the possible stack options?

All the best

**Comment by josegonzalez** [comment]
We haven't supported heroku-22 since their setup wasn't completed until somewhat recently (not even sure all official heroku buildpacks are supported still).

We'd need an MR to add that functionality.

**Comment by tadeoos** [comment]
Understood, thanks for a quick reply!

**Comment by josegonzalez** [comment]
There is an MR open for this btw: https://github.com/gliderlabs/herokuish/pull/792
