### ISSUE TITLE
Procfile parsing seems very fragile

### ISSUE THREAD

**Issue by andor44** [gliderlabs/herokuish#80]
Earlier today, while trying to deploy an app to Dokku I had a simple Procfile which looked like this
```
web:python server.py
```

Can you spot the error? Yeah, I couldn't either. As it turns out, herokuish expects a space after the colon and threw [this](https://gist.github.com/andor44/00ea298f6795dc383549) nasty stack trace in my face. Neither foreman nor "real" Heroku seems to care about the presence of the space, or lack thereof. The error message is also really cryptic and nondescript, and it was just really a random guess of mine to try it with a space. A better error message, or more lenient parsing of the Procfile would be really nice.

**Comment by progrium** [comment]
Perhaps our YAML library is too picky. Since it's never more complex YAML, we could switch to basic string splitting mechanisms that would be more robust.
