### ISSUE TITLE
Cannot install on Rocky 8.6/8.7 - Permission denied

### ISSUE THREAD

**Issue by dougc84** [gliderlabs/herokuish#878]
I'm trying to get `herokuish` and `dokku` working on a Rocky Linux 8.6 droplet on Digital Ocean. Docker is installed and is running without any issues using the Docker CE repo.

However, because post-install does not work, in turn, `dokku` doesn't either.

Here's the terminal output:

<img width="2139" alt="Screen Shot 2023-02-20 at 6 42 10 PM" src="https://user-images.githubusercontent.com/744509/220213680-3afb502e-12e3-4342-a32c-f9e21821731f.png">

**Comment by josegonzalez** [comment]
Note: Dokku does not support anything other than Ubuntu and Debian out of the box (we drop RHEL support a few releases back). I'm also inclined to do nothing here as a result.

If you want to install Dokku on that machine, you can try running the container directly: https://dokku.com/docs/getting-started/install/docker/
