### ISSUE TITLE
Heroku stack images got updated, missing packages used by a buildpack

### ISSUE THREAD

**Issue by kiskoza** [gliderlabs/herokuish#892]
Recently I ran into an issue with [heroku-buildpack-activestorage-preview](https://github.com/heroku/heroku-buildpack-activestorage-preview/issues/41) and it turned out that there's nothing wrong with the buildpack itself, they just started to rely on a package that was added into the heroku stack images, mentioned here: https://devcenter.heroku.com/changelog-items/2547

As far as I know the latest herokuish images was built 4 months ago back in November, so they don't have the new packages added in February, but it could be solved by just releasing a new version that automatically gets the new install scripts from heroku's repo.

**Comment by josegonzalez** [comment]
Mind checking if the latest release handles this? I just fixed pipelines so hopefully you're all clear here.

**Comment by josegonzalez** [comment]
Ugh looks like the release step failed for other reasons... I'll take a look again tonight. Gonna yank that package for now.

**Comment by josegonzalez** [comment]
Okay I think I re-released the stacks properly now. Mind checking if everything works as expected?
